
shared:
  api_key: 123

development:
  secret_key_base: 1fe3edb870eff077105cff3ed19f0bdf15a5f999ef09ba1043a4916

test:
  secret_key_base: 8baba343e347eadbfcbfa77afb3ba0b13b403fa2dcfb643edf18e44
  twitter_api_key: "FuiCOb9knp5USp6Si1rlAscHa"
  twitter_api_secret: "WYcZZdrPBteO4UCbjqFDfm8SakmeVILgO3tJ7SFADwqLjnPNsJ"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
