# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#
development: &default
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: fc65272c27199652b936c28264bf770f385243f00d91b69f7424ca298466
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>
  host_name: "6e0fd751.ngrok.com"
  rollbar: '7f4b0337a9c14f069cb41c1738298fee'

test:
  <<: *default
  secret_key_base: 8489bb21c9497da574dcb42fea4e15d089606d196e367f6f4e166acb281d
#

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
